spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 42300

